/**
 * Worker bindings. `Env` (vars + bindings declared in wrangler.jsonc) is generated by
 * `wrangler types`; secrets are added here because they are not declared in config.
 */
export interface Bindings extends Env {
  SUPABASE_URL?: string;
  SUPABASE_ANON_KEY?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
  SUPABASE_DB_URL?: string;
  SUPABASE_JWT_SECRET?: string;
  BOOTSTRAP_ADMIN_PASSWORD?: string;
  HYPERDRIVE?: Hyperdrive;
}

export function demoControlsEnabled(env: Pick<Bindings, 'DEMO_CONTROLS'>): boolean {
  return String(env.DEMO_CONTROLS) === 'true';
}
